using Oscar
using LinearAlgebra
using HomotopyContinuation
using Plots 

# PRE: V is a collection of vertices (points) defining a full-dimensional convex polytope.
# POST: Returns the volume of the convex hull of the vertices in V.
function areaofpolyhedra(V)
    P = convex_hull(QQ,V)
    return volume(P)
end

# PRE: v is a point, and h is a vector of coefficients defining a hyperplane
#      h₁x₁ + ⋯ + hₙxₙ = t, where h = [h₁, …, hₙ, -t].
# POST: Returns the evaluation of the hyperplane equation at v, i.e., the inner
#       product h ⋅ (v, -1). The result is zero if v lies on the hyperplane,
#       positive or negative depending on the side of the hyperplane.
function inner_product(v,h)
    S = parent(v[1])
    v_lift = [S(x) for x in v]
    push!(v_lift, -S(1))
    s = sum(h[i]*v_lift[i] for i in 1:length(h))
    return s
end

# PRE: V is a collection of points in R^d.
# POST: Returns the collection {(v, -1) : v ∈ V} in R^{d+1}.
function vertex_embed(V)
    embedding = Vector{Vector{QQFieldElem}}()
    for v in V
        #println(v)
        v_lift = copy(v)
        #println(v_lift)
        push!(v_lift,-1)
        push!(embedding,v_lift)
    end
    return embedding
end

# PRE: V is a collection of vertices spanning a polytope, and h is a vector of
#      coefficients defining the hyperplane H = {x : h ⋅ (x, -1) = 0}.
# POST: Returns the facets of the convex hull of V whose endpoints lie on
#       opposite sides of H (or with one endpoint on H), i.e., the edges
#       intersected by the hyperplane H.
function hyperplane_intersect(V,h)
	P = convex_hull(QQ,V)
	cut = []
    
	for facet in faces(P, Oscar.ambient_dim(P)-1)
        #println(facet)
		s = [inner_product(collect(v),h) for v in vertices(facet)]
        t = 0
        #find the first non-zero value in the vector s
        for i in 1:length(s)
            if s[i] != 0
                t = s[i]
                break
            end
        end
        is_cut = false
        #if there is some value on s of opposite sign as t, push the face into cut
		for r in s
            if (r != 0 && sign(r) != sign(t))
                is_cut = true
                break
            end
        end
        if is_cut
            push!(cut,facet)
        end
	end
	return cut 
end
    
# PRE: V is a collection of vertices spanning a polytope, and h is a vector of
#      coefficients defining the hyperplane H = {x : h ⋅ (x, -1) = 0}.
# POST: Returns the distinct intersection points between H and the edges of the
#       convex hull of V.
function hyperplane_intersectpoints(V,h)
    facets = hyperplane_intersect(V,h)
    newpoints = Vector{Vector{QQFieldElem}}()
    points = Vector{Vector{QQFieldElem}}()
    for facet in facets
        for f in faces(facet, 1)
            v = [collect(vv) for vv in vertices(f)]
            s1 = inner_product(v[2],h)
            s2 = inner_product(v[1],h)
            if s1 * s2 <= 0 && !(s1 == 0 && s2 == 0)
                l = s1 //(s1 - s2)
                p = [l*v[1][i] + (1-l)*v[2][i] for i in 1:length(v[1])]
                push!(points, p)
            end
        end
    end
    for p in points
        if !(p in newpoints)
            push!(newpoints,p)
        end
    end
return newpoints
end

# PRE: V is a collection of vertices spanning a polytope, and h is a vector of
#      coefficients defining the hyperplane H = {x : h ⋅ (x, -1) = 0}.
# POST: Returns the volume of P(h < 0), i.e. P ∩ {x : h ⋅ (x,-1) < 0}.
function negative_volumeofcut(V,h)
    newpoints = hyperplane_intersectpoints(V,h)
    points = Vector{Vector{QQFieldElem}}()
    for v in V
        s = inner_product(v,h)
        if s < 0
            push!(points, v)        
        end
    end
    for v in newpoints
        push!(points, v)
    end    
    Pneg = convex_hull(QQ, points)
    return(volume(Pneg))
end    


# PRE: V is a collection of vertices spanning a polytope in R^d.
# POST: Returns the maximal open chambers of the hyperplane arrangement
#       induced by the hyperplanes defined by the embedded vertices (v, -1).
function get_chambers(V)
    n = length(V)
    embed = vertex_embed(V)
    ha = transpose(reduce(hcat, embed))
    HA = Polymake.fan.HyperplaneArrangement(HYPERPLANES=ha)
    CD = HA.CHAMBER_DECOMPOSITION
    
    fan = polyhedral_fan(CD)
    chambers = maximal_cones(fan)
    return chambers
end


# PRE: V is a collection of vertices defining a polytope in R^d.
# POST: Returns a collection of pairs (C, h), where C is a non-empty maximal
#       chamber of the hyperplane arrangement generated by V and h is a
#       representative vector lying in the interior of C.
function representing_vectors(V)
    chambers = get_chambers(V)
    reprvec = []
    d = length(V[1])
    for ch in chambers
        h = sum(rays(ch))
        edgecut = hyperplane_intersect(V, h)
        if length(edgecut) > d-1
            #instead of push!(reprvec, h). This converts h from RayVEctor to Vector{QQFieldElem} -> needed?
            push!(reprvec, (chamber = ch, repr = collect(QQFieldElem, h)))
        end
    end
    return reprvec
end

# PRE: sx is a list of k vertices defining a (k-1)-dimensional simplex, and S is
#      the fraction field containing the coordinates of the vertices.
# POST: Returns the volume of the simplex computed as det(M)/(k-1)!,
#       where M is the matrix whose columns are the edge vectors
#       sx[i] - sx[1] for i = 2,...,k.
function vol_simplex(sx,S)
    k = length(sx)
    columns = [sx[i] - sx[1] for i in 2:k]
    M = reduce(hcat, columns)
    #println(M)
    M_matrix = matrix(S, M)
    volume = Oscar.det(M_matrix)//factorial(k-1)
    return volume
end


# PRE: V is a collection of vertices spanning a polytope in R^d, and h is a
#      vector representing a chamber of the hyperplane arrangement. The
#      corresponding symbolic hyperplane has coefficients (h₁,...,h_{d+1})
#      and is defined by H = {x : h ⋅ (x,-1) = 0}.
# POST: Returns the numerical and the symbolic intersection points of 
#       the edges of the polytope with the hyperplane H. The symbolic
#       points are represented as rational functions in the hyperplane
#       coefficients.
function symbolic_intersection(V,h)
    d = length(V[1])
    variables = ["h$i" for i in 1:d+1]
    P = convex_hull(QQ,V)
    R, vars = polynomial_ring(QQ, variables)
    S = fraction_field(R)

    c = [S(v) for v in vars]
    #this gives the facets getting cut by a hyperplane with coefficients lying in the chamber represented by h
    
    points_num = Vector{Vector{QQFieldElem}}()
    points_sym = Vector{Vector{eltype(S)}}()

     for v in V
        s = inner_product(v,h) 
        if s < 0 #what about = 0?
            push!(points_num, v)
            push!(points_sym, [S(x) for x in v])
        end
    end
        
    for f in faces(P, 1)
        v = [collect(vv) for vv in vertices(f)]
        s1_num = inner_product(v[2],h)
        s2_num = inner_product(v[1],h)

        s1 = inner_product([S(w) for w in v[2]],c)
        s2 = inner_product([S(w) for w in v[1]],c)
        
        if s1_num * s2_num <= 0 && !(s1_num == 0 && s2_num == 0)
            l_num = s1_num //(s1_num - s2_num)
            l_sym = s1 //(s1 - s2)
            
            p_sym = [l_sym*S(v[1][i]) + (1-l_sym)*S(v[2][i]) for i in 1:length(v[1])]
            p_num = [l_num*v[1][i] + (1-l_num)*v[2][i] for i in 1:length(v[1])]
                            
            push!(points_num, p_num)
            push!(points_sym,p_sym)
        end
    end

    return points_num, points_sym, S
end


# PRE: V is a set of vertices defining a polytope in R^d, and h lies in a
#      maximal open chamber of the hyperplane arrangement induced by V.
# POST: Returns a pair (num, sym), where num is the exact volume of the cut
#       polytope for the representative h, and sym is the rational function in
#       the hyperplane coefficients giving the volume for any h in the same
#       chamber.
function local_volume(V,h)
    #now we take a look at the points numerically and symbolically
    points_num, points_sym, S = symbolic_intersection(V,h)
    #create a convex hull of the numerical intersection using the representative and take its triangulation 
    Pplus = convex_hull(QQ, points_num)
    #this gives me the indices of the vertices needed
    triang = regular_triangulation(Pplus)

    #now to compute a rational volume function, we create a list of vertices, where the representative intersection 
    #points are substituted by the corresponding functions
    volume_sym = S(0)
    volume_num = QQ(0)
    for index in triang[1]
        sx_num = points_num[index]
        sx_sym = points_sym[index]
        #println(sx)
        volume_num += vol_simplex(sx_num, QQ)
        volume_sym += sign(vol_simplex(sx_num, QQ))*vol_simplex(sx_sym, S)
    end
    volume = (num = volume_num, sym = volume_sym)
    return volume
end


# PRE: V is a set of vertices defining a polytope P ⊂ R^d.
# POST: Returns a list of triples (C, h, f_C), where C is a non-empty maximal
#       chamber of the induced hyperplane arrangement, h is a representative
#       vector in C, and f_C is the rational function giving the volume of the
#       corresponding cut polytope for all hyperplanes with coefficients in C.
function volume_functions(V)
    reprvec = representing_vectors(V)
    functions = []

    for item in reprvec
        h = item.repr
        ch = item.chamber
        
        vol = local_volume(V,h)
        
        push!(functions, (chamber = ch, repr = h, local_vol = vol.sym))
    end
    return functions
end

# PRE: V is a set of vertices defining a polytope in R^d.
# POST: Returns a list of triples (C, h, g_C), where C is a chamber of the
#       hyperplane arrangement, h is a representative vector of C, and
#       g_C = 2p - A*q is the polynomial equation whose solutions correspond to
#       hyperplanes in C that halve the volume of P, with f_C = p/q the local
#       volume function and A = vol(P).
function halving_equations(V)
    d = length(V[1])
    variables = ["h$i" for i in 1:d+1]
    R, vars = polynomial_ring(QQ, variables)
    S = fraction_field(R)

    vol_loc = volume_functions(V)
    area = areaofpolyhedra(V)
    equations = []
    
    for tuple in vol_loc
        ch = tuple.chamber
        fct = tuple.local_vol
        p = numerator(fct)
        q = denominator(fct)
        f = 2*p - area*q
        push!(equations,(chamber = ch, repr= tuple.repr, volume_ch = f ))
    end
    return equations
end

# PRE: f ∈ k[x₁,...,xₙ] is an Oscar polynomial and vars = [x₁,...,xₙ] is the
#      corresponding list of variables.
# POST: Returns the same polynomial f represented as a
#       HomotopyContinuation.Expression.
function oscar_to_homcon(f,vars)
    result = HomotopyContinuation.Expression(0)
    n = length(vars)
    for t in terms(f)
        c = collect(AbstractAlgebra.coefficients(t))
        e = collect(AbstractAlgebra.exponent_vectors(t))
        monom = prod(vars[i]^e[1][i] for i in 1:n)
        coeff = numerator(c[1])//denominator(c[1])
        term = Rational(coeff)*monom
        result += term
    end
    return result
end

# PRE: P_1,...,P_n are polytopes in R^d with n <= d and non-zero volume.
# POST: Returns coefficient vectors h defining hyperplanes H = {x :h ⋅ (x,-1) = 0} 
#       such that each H cuts every polytope P_i into a region of volume alpha_i * vol(P_i).
function ham_sandwich(polytopes)
    d = Oscar.dim(polytopes[1])
    @assert(length(polytopes) <= d)
    vertices_list = [[collect(v) for v in vertices(P)] for P in polytopes]

    for V in vertices_list
        if (length(V) < d)
            println("One of the Polygons is degenerate")
            return
        end
    end
    L = [halving_equations(V) for V in vertices_list]

    halves= [Float64(areaofpolyhedra(V))/2 for V in vertices_list]

    @var h[1:d+1]
    vars = collect(h)
    solutions = []
    
    for combinations in Iterators.product(L...)
        combinations = collect(combinations)
        fcts_hc = HomotopyContinuation.Expression[]
        skip = false

        for tuple in combinations
            f_hc = oscar_to_homcon(tuple.volume_ch, vars)
            if isempty(variables(f_hc))
                skip = true
                break
            end
            push!(fcts_hc, f_hc)
        end
        skip && continue
        cc = reduce(intersect, [tuple.chamber for tuple in combinations])
        
        if Oscar.dim(cc) == d+1
            normalizer = sum(vars[i]^2 for i in 1:d)-1
            push!(fcts_hc, normalizer)
            F = HomotopyContinuation.solve(fcts_hc)
            points = HomotopyContinuation.real_solutions(F) 
            #in_cc = [v for v in points if v in cc]
            for sol in points
               if sol in cc
                coeff = [QQ(rationalize(BigFloat(x))) for x in sol]
                cuts = [Float64(nnegative_volumeofcut(V, coeff)) for V in vertices_list]
                    if all(abs(cuts[i] - halves[i]) < 1e-6 for i in 1:length(polytopes))
                        push!(solutions, sol)
                    end
                end
            end
        end
    end
    return solutions
end


# function main()
#     V1 = [
#     [0, 0, 0],
#     [1, 0, 0],
#     [0, 1, 0],
#     [0, 0, 1]
#     ]
    
#     V2 = [
#     [1, 0, 0],
#     [2, 0, 0],
#     [1, 1, 0],
#     [1, 0, 1]
#     ]
    
#     V3 = [
#     [0, 1, 0],
#     [1, 1, 0],
#     [0, 2, 0],
#     [0, 1, 1]
#     ]
    
    
#     P = convex_hull(QQ, V1)
#     Q = convex_hull(QQ, V2)
#     T = convex_hull(QQ, V3)
#     println(ham_sandwich([P,Q,T]))
# end
# main()

# function main()
#     V1 = [
#         [QQ(4), QQ(1)],
#         [QQ(5), QQ(3)],
#         [QQ(2), QQ(4)],
#         [QQ(0), QQ(2)],
#         [QQ(1), QQ(1)]
#     ]

#     V2 = [
#         [QQ(-4), QQ(-3)],
#         [QQ(-2), QQ(-1)],
#         [QQ(1), QQ(-2)],
#         [QQ(2), QQ(-5)],
#         [QQ(-1), QQ(-6)],
#         [QQ(-3), QQ(-5)]
#     ]

#     P = convex_hull(QQ,V1)
#     Q = convex_hull(QQ,V2)

#     solutions = ham_sandwich([P,Q])

#     println("Number of solutions: ", length(solutions))

#     for (i,sol) in enumerate(solutions)
#         println("\nSolution $i")
#         println("h = ", sol)

#         println("P cut volume = ",
#             Float64(negative_volumeofcut(V1,
#             [QQ(rationalize(BigFloat(x))) for x in sol])))

#         println("Q cut volume = ",
#             Float64(negative_volumeofcut(V2,
#             [QQ(rationalize(BigFloat(x))) for x in sol])))

#         println("Expected P half = ",
#             Float64(areaofpolyhedra(V1)/2))

#         println("Expected Q half = ",
#             Float64(areaofpolyhedra(V2)/2))
#     end
# end
# main()

function main()

# --- Build the three tetrahedra ---
    V1 = [
        [QQ(0), QQ(0), QQ(0)],
        [QQ(1), QQ(0), QQ(0)],
        [QQ(0), QQ(1), QQ(0)],
        [QQ(0), QQ(0), QQ(1)]
    ]
    V2 = [
        [QQ(2), QQ(0), QQ(0)],
        [QQ(3), QQ(0), QQ(0)],
        [QQ(2), QQ(1), QQ(0)],
        [QQ(2), QQ(0), QQ(1)]
    ]
    V3 = [
        [QQ(0), QQ(2), QQ(0)],
        [QQ(1), QQ(2), QQ(0)],
        [QQ(0), QQ(3), QQ(0)],
        [QQ(0), QQ(2), QQ(1)]
    ]
    
    # Create Oscar polytopes
    P1 = convex_hull(QQ, V1)
    P2 = convex_hull(QQ, V2)
    P3 = convex_hull(QQ, V3)
    polytopes = [P1, P2, P3]
    vertex_sets = [V1, V2, V3]
    
    # --- Volumes (3D analogue of "area") ---
    vol_P1 = areaofpolyhedra(V1)
    vol_P2 = areaofpolyhedra(V2)
    vol_P3 = areaofpolyhedra(V3)
    
    println("Volume of P1 = ", vol_P1, " ≈ ", Float64(vol_P1))
    println("Volume of P2 = ", vol_P2, " ≈ ", Float64(vol_P2))
    println("Volume of P3 = ", vol_P3, " ≈ ", Float64(vol_P3))
    
    println("Half volume of P1 = ", vol_P1 // 2, " ≈ ", Float64(vol_P1 // 2))
    println("Half volume of P2 = ", vol_P2 // 2, " ≈ ", Float64(vol_P2 // 2))
    println("Half volume of P3 = ", vol_P3 // 2, " ≈ ", Float64(vol_P3 // 2))
    
    # --- Ham sandwich cut: now a plane a*x + b*y + c*z = d bisecting all three solids ---
    solutions = ham_sandwich(polytopes)
    println("Ham sandwich solutions: ", solutions)
    
    for (i, sol) in enumerate(solutions)
        a0 = QQ(rationalize(sol[1]))
        b0 = QQ(rationalize(sol[2]))
        c0 = QQ(rationalize(sol[3]))
        d0 = QQ(rationalize(sol[4]))
    
        cut_P1 = negative_volumeofcut(V1, a0, b0, c0, d0)
        cut_P2 = negative_volumeofcut(V2, a0, b0, c0, d0)
        cut_P3 = negative_volumeofcut(V3, a0, b0, c0, d0)
    
        println("\nSolution $i: a=$a0, b=$b0, c=$c0, d=$d0")
        println("  Volume cut of P1 = ", Float64(cut_P1),
                " (target = ", vol_P1 // 2, " ≈ ", Float64(vol_P1 // 2), ")")
        println("  Volume cut of P2 = ", Float64(cut_P2),
                " (target = ", vol_P2 // 2, " ≈ ", Float64(vol_P2 // 2), ")")
        println("  Volume cut of P3 = ", Float64(cut_P3),
                " (target = ", vol_P3 // 2, " ≈ ", Float64(vol_P3 // 2), ")")
    end
end
main()